import { DietaryRestriction, NutritionTier } from '../../profile/enums';
import { DayTemplate, Ingredient, MealType } from '../entities';

export interface MealTemplateSeedData {
  slug: string;
  name: string;
  tier: NutritionTier;
  mealType: MealType;
  dayTemplate: DayTemplate;
  calories: number;
  proteinG: number;
  fatG: number;
  carbsG: number;
  ingredients: Ingredient[];
  instructions?: string;
  dietaryTags?: DietaryRestriction[];
}

export const MEAL_TEMPLATES_SEED: MealTemplateSeedData[] = [
  // ============= BUDGET =============
  {
    slug: 'budget_oats_milk_banana',
    name: 'Овсянка + молоко + банан',
    tier: NutritionTier.BUDGET,
    mealType: 'breakfast',
    dayTemplate: 'training_day',
    calories: 520, proteinG: 22, fatG: 12, carbsG: 80,
    ingredients: [
      { name: 'Овсянка', amount: 80, unit: 'г' },
      { name: 'Молоко 2.5%', amount: 250, unit: 'мл' },
      { name: 'Банан', amount: 1, unit: 'шт.' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },
  {
    slug: 'budget_buckwheat_eggs',
    name: 'Гречка + яйца + овощи',
    tier: NutritionTier.BUDGET,
    mealType: 'lunch',
    dayTemplate: 'training_day',
    calories: 600, proteinG: 32, fatG: 15, carbsG: 85,
    ingredients: [
      { name: 'Гречка (сухая)', amount: 100, unit: 'г' },
      { name: 'Яйцо', amount: 3, unit: 'шт.' },
      { name: 'Замороженные овощи', amount: 200, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'budget_rice_chicken',
    name: 'Рис + курица + замороженные овощи',
    tier: NutritionTier.BUDGET,
    mealType: 'dinner',
    dayTemplate: 'training_day',
    calories: 650, proteinG: 45, fatG: 14, carbsG: 90,
    ingredients: [
      { name: 'Рис (сухой)', amount: 100, unit: 'г' },
      { name: 'Куриная грудка', amount: 200, unit: 'г' },
      { name: 'Замороженные овощи', amount: 200, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE, DietaryRestriction.HALAL],
  },
  {
    slug: 'budget_tvorog_berries',
    name: 'Творог + ягоды',
    tier: NutritionTier.BUDGET,
    mealType: 'snack',
    dayTemplate: 'training_day',
    calories: 280, proteinG: 30, fatG: 7, carbsG: 22,
    ingredients: [
      { name: 'Творог 5%', amount: 200, unit: 'г' },
      { name: 'Ягоды замороженные', amount: 100, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'budget_pasta_canned_tuna',
    name: 'Паста + консервированный тунец',
    tier: NutritionTier.BUDGET,
    mealType: 'lunch',
    dayTemplate: 'rest_day',
    calories: 560, proteinG: 35, fatG: 10, carbsG: 85,
    ingredients: [
      { name: 'Паста (сухая)', amount: 100, unit: 'г' },
      { name: 'Тунец в с/с', amount: 150, unit: 'г' },
      { name: 'Помидор', amount: 1, unit: 'шт.' },
    ],
  },
  {
    slug: 'budget_potato_eggs',
    name: 'Картофель + яичница',
    tier: NutritionTier.BUDGET,
    mealType: 'breakfast',
    dayTemplate: 'rest_day',
    calories: 480, proteinG: 22, fatG: 18, carbsG: 55,
    ingredients: [
      { name: 'Картофель', amount: 300, unit: 'г' },
      { name: 'Яйцо', amount: 3, unit: 'шт.' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'budget_lentil_soup',
    name: 'Чечевичный суп с овощами',
    tier: NutritionTier.BUDGET,
    mealType: 'lunch',
    dayTemplate: 'rest_day',
    calories: 420, proteinG: 24, fatG: 8, carbsG: 62,
    ingredients: [
      { name: 'Чечевица', amount: 80, unit: 'г' },
      { name: 'Овощи (морковь, лук)', amount: 150, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.VEGAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'budget_kefir_oats_snack',
    name: 'Кефир + геркулес',
    tier: NutritionTier.BUDGET,
    mealType: 'snack',
    dayTemplate: 'rest_day',
    calories: 240, proteinG: 14, fatG: 6, carbsG: 35,
    ingredients: [
      { name: 'Кефир 1%', amount: 250, unit: 'мл' },
      { name: 'Овсянка', amount: 40, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },
  {
    slug: 'budget_beans_rice',
    name: 'Фасоль + рис (веган)',
    tier: NutritionTier.BUDGET,
    mealType: 'dinner',
    dayTemplate: 'rest_day',
    calories: 520, proteinG: 22, fatG: 5, carbsG: 100,
    ingredients: [
      { name: 'Фасоль отварная', amount: 200, unit: 'г' },
      { name: 'Рис', amount: 80, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.VEGAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'budget_bread_egg_apple',
    name: 'Хлеб + яйцо + яблоко',
    tier: NutritionTier.BUDGET,
    mealType: 'snack',
    dayTemplate: 'training_day',
    calories: 300, proteinG: 15, fatG: 8, carbsG: 42,
    ingredients: [
      { name: 'Хлеб цельнозерновой', amount: 60, unit: 'г' },
      { name: 'Яйцо', amount: 2, unit: 'шт.' },
      { name: 'Яблоко', amount: 1, unit: 'шт.' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },

  // ============= STANDARD =============
  {
    slug: 'standard_omelette_oats',
    name: 'Омлет + овсянка + фрукт',
    tier: NutritionTier.STANDARD,
    mealType: 'breakfast',
    dayTemplate: 'training_day',
    calories: 560, proteinG: 35, fatG: 18, carbsG: 65,
    ingredients: [
      { name: 'Яйцо', amount: 3, unit: 'шт.' },
      { name: 'Овсянка', amount: 60, unit: 'г' },
      { name: 'Ягоды свежие', amount: 100, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },
  {
    slug: 'standard_fish_potato',
    name: 'Рыба + картофель + салат',
    tier: NutritionTier.STANDARD,
    mealType: 'lunch',
    dayTemplate: 'training_day',
    calories: 620, proteinG: 42, fatG: 18, carbsG: 65,
    ingredients: [
      { name: 'Лосось / треска', amount: 180, unit: 'г' },
      { name: 'Картофель запечённый', amount: 250, unit: 'г' },
      { name: 'Салат овощной', amount: 150, unit: 'г' },
      { name: 'Оливковое масло', amount: 10, unit: 'мл' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'standard_chicken_salad',
    name: 'Салат с курицей и булгуром',
    tier: NutritionTier.STANDARD,
    mealType: 'lunch',
    dayTemplate: 'rest_day',
    calories: 540, proteinG: 40, fatG: 14, carbsG: 60,
    ingredients: [
      { name: 'Куриная грудка', amount: 180, unit: 'г' },
      { name: 'Булгур', amount: 70, unit: 'г' },
      { name: 'Овощи + зелень', amount: 150, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.HALAL],
  },
  {
    slug: 'standard_greek_yogurt_nuts',
    name: 'Греческий йогурт + орехи + ягоды',
    tier: NutritionTier.STANDARD,
    mealType: 'snack',
    dayTemplate: 'training_day',
    calories: 320, proteinG: 20, fatG: 16, carbsG: 22,
    ingredients: [
      { name: 'Греческий йогурт', amount: 200, unit: 'г' },
      { name: 'Миндаль', amount: 20, unit: 'г' },
      { name: 'Ягоды свежие', amount: 80, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'standard_beef_rice',
    name: 'Говядина + бурый рис + овощи',
    tier: NutritionTier.STANDARD,
    mealType: 'dinner',
    dayTemplate: 'training_day',
    calories: 680, proteinG: 45, fatG: 22, carbsG: 70,
    ingredients: [
      { name: 'Говядина постная', amount: 180, unit: 'г' },
      { name: 'Бурый рис', amount: 90, unit: 'г' },
      { name: 'Брокколи / зелёная фасоль', amount: 200, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'standard_tofu_quinoa',
    name: 'Тофу + киноа + овощи (веган)',
    tier: NutritionTier.STANDARD,
    mealType: 'dinner',
    dayTemplate: 'rest_day',
    calories: 560, proteinG: 32, fatG: 18, carbsG: 65,
    ingredients: [
      { name: 'Тофу', amount: 200, unit: 'г' },
      { name: 'Киноа', amount: 80, unit: 'г' },
      { name: 'Овощи на пару', amount: 200, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.VEGAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'standard_tuna_sandwich',
    name: 'Сэндвич с тунцом + овощи',
    tier: NutritionTier.STANDARD,
    mealType: 'snack',
    dayTemplate: 'rest_day',
    calories: 380, proteinG: 28, fatG: 10, carbsG: 45,
    ingredients: [
      { name: 'Хлеб цельнозерновой', amount: 80, unit: 'г' },
      { name: 'Тунец', amount: 100, unit: 'г' },
      { name: 'Огурец + помидор', amount: 100, unit: 'г' },
    ],
  },
  {
    slug: 'standard_salmon_avocado',
    name: 'Лосось + авокадо + киноа',
    tier: NutritionTier.STANDARD,
    mealType: 'dinner',
    dayTemplate: 'heavy_training_day',
    calories: 720, proteinG: 44, fatG: 28, carbsG: 62,
    ingredients: [
      { name: 'Лосось', amount: 180, unit: 'г' },
      { name: 'Авокадо', amount: 0.5, unit: 'шт.' },
      { name: 'Киноа', amount: 80, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'standard_protein_smoothie',
    name: 'Протеиновый смузи (банан + молоко + овсянка)',
    tier: NutritionTier.STANDARD,
    mealType: 'snack',
    dayTemplate: 'training_day',
    calories: 340, proteinG: 28, fatG: 5, carbsG: 48,
    ingredients: [
      { name: 'Банан', amount: 1, unit: 'шт.' },
      { name: 'Молоко 1.5%', amount: 300, unit: 'мл' },
      { name: 'Овсянка', amount: 40, unit: 'г' },
      { name: 'Протеин (whey)', amount: 20, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },
  {
    slug: 'standard_eggs_avocado_toast',
    name: 'Тост + авокадо + яйцо-пашот',
    tier: NutritionTier.STANDARD,
    mealType: 'breakfast',
    dayTemplate: 'rest_day',
    calories: 460, proteinG: 20, fatG: 24, carbsG: 40,
    ingredients: [
      { name: 'Хлеб цельнозерновой', amount: 80, unit: 'г' },
      { name: 'Авокадо', amount: 0.5, unit: 'шт.' },
      { name: 'Яйцо', amount: 2, unit: 'шт.' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },

  // ============= ADVANCED =============
  {
    slug: 'advanced_pre_workout_rice_chicken',
    name: 'Pre-workout: рис + курица + банан (за 1–3ч до)',
    tier: NutritionTier.ADVANCED,
    mealType: 'pre_workout',
    dayTemplate: 'heavy_training_day',
    calories: 550, proteinG: 36, fatG: 5, carbsG: 90,
    ingredients: [
      { name: 'Рис белый', amount: 100, unit: 'г' },
      { name: 'Куриная грудка', amount: 150, unit: 'г' },
      { name: 'Банан', amount: 1, unit: 'шт.' },
    ],
    instructions: 'Есть за 1–3 часа до тренировки (проверять переносимость).',
    dietaryTags: [DietaryRestriction.GLUTEN_FREE, DietaryRestriction.HALAL],
  },
  {
    slug: 'advanced_post_workout_whey_banana',
    name: 'Post-workout: whey + банан + молоко',
    tier: NutritionTier.ADVANCED,
    mealType: 'post_workout',
    dayTemplate: 'heavy_training_day',
    calories: 360, proteinG: 32, fatG: 4, carbsG: 52,
    ingredients: [
      { name: 'Whey protein', amount: 30, unit: 'г' },
      { name: 'Банан', amount: 1, unit: 'шт.' },
      { name: 'Молоко 1.5%', amount: 300, unit: 'мл' },
    ],
    instructions: 'В течение 1–2 часов после тренировки, если удобно.',
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },
  {
    slug: 'advanced_breakfast_eggs_oats_berries',
    name: 'Завтрак: 4 яйца + овсянка + ягоды',
    tier: NutritionTier.ADVANCED,
    mealType: 'breakfast',
    dayTemplate: 'training_day',
    calories: 620, proteinG: 40, fatG: 22, carbsG: 60,
    ingredients: [
      { name: 'Яйцо целое', amount: 2, unit: 'шт.' },
      { name: 'Яичный белок', amount: 4, unit: 'шт.' },
      { name: 'Овсянка', amount: 60, unit: 'г' },
      { name: 'Ягоды', amount: 100, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },
  {
    slug: 'advanced_lunch_chicken_sweet_potato',
    name: 'Обед: куриная грудка + батат + овощи',
    tier: NutritionTier.ADVANCED,
    mealType: 'lunch',
    dayTemplate: 'training_day',
    calories: 620, proteinG: 48, fatG: 12, carbsG: 75,
    ingredients: [
      { name: 'Куриная грудка', amount: 200, unit: 'г' },
      { name: 'Батат', amount: 250, unit: 'г' },
      { name: 'Зелёные овощи', amount: 200, unit: 'г' },
      { name: 'Оливковое масло', amount: 10, unit: 'мл' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE, DietaryRestriction.HALAL],
  },
  {
    slug: 'advanced_dinner_steak_rice',
    name: 'Ужин: стейк + рис + брокколи',
    tier: NutritionTier.ADVANCED,
    mealType: 'dinner',
    dayTemplate: 'heavy_training_day',
    calories: 720, proteinG: 50, fatG: 22, carbsG: 75,
    ingredients: [
      { name: 'Говяжий стейк постный', amount: 200, unit: 'г' },
      { name: 'Бурый рис', amount: 90, unit: 'г' },
      { name: 'Брокколи', amount: 200, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'advanced_casein_before_sleep',
    name: 'Казеин перед сном (медленный белок)',
    tier: NutritionTier.ADVANCED,
    mealType: 'snack',
    dayTemplate: 'heavy_training_day',
    calories: 220, proteinG: 28, fatG: 6, carbsG: 12,
    ingredients: [
      { name: 'Casein protein', amount: 30, unit: 'г' },
      { name: 'Молоко / вода', amount: 250, unit: 'мл' },
    ],
    instructions: 'За 30–60 мин до сна, на восстановительных днях.',
    dietaryTags: [DietaryRestriction.VEGETARIAN],
  },
  {
    slug: 'advanced_deload_lower_carb_salad',
    name: 'Deload: салат с курицей + мало углеводов',
    tier: NutritionTier.ADVANCED,
    mealType: 'dinner',
    dayTemplate: 'rest_day',
    calories: 440, proteinG: 40, fatG: 18, carbsG: 25,
    ingredients: [
      { name: 'Куриная грудка', amount: 180, unit: 'г' },
      { name: 'Микс салата', amount: 200, unit: 'г' },
      { name: 'Оливковое масло', amount: 15, unit: 'мл' },
      { name: 'Киноа', amount: 30, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE, DietaryRestriction.HALAL],
  },
  {
    slug: 'advanced_pre_workout_vegan',
    name: 'Pre-workout (веган): овсянка + банан + соевый протеин',
    tier: NutritionTier.ADVANCED,
    mealType: 'pre_workout',
    dayTemplate: 'training_day',
    calories: 480, proteinG: 32, fatG: 6, carbsG: 78,
    ingredients: [
      { name: 'Овсянка', amount: 70, unit: 'г' },
      { name: 'Банан', amount: 1, unit: 'шт.' },
      { name: 'Соевый протеин', amount: 30, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.VEGAN],
  },
  {
    slug: 'advanced_snack_cottage_cheese_nuts',
    name: 'Перекус: творог + орехи + мёд',
    tier: NutritionTier.ADVANCED,
    mealType: 'snack',
    dayTemplate: 'training_day',
    calories: 360, proteinG: 28, fatG: 16, carbsG: 24,
    ingredients: [
      { name: 'Творог 5%', amount: 200, unit: 'г' },
      { name: 'Грецкий орех', amount: 20, unit: 'г' },
      { name: 'Мёд', amount: 10, unit: 'г' },
    ],
    dietaryTags: [DietaryRestriction.VEGETARIAN, DietaryRestriction.GLUTEN_FREE],
  },
  {
    slug: 'advanced_lunch_salmon_bowl',
    name: 'Обед: боул с лососем + киноа + овощи',
    tier: NutritionTier.ADVANCED,
    mealType: 'lunch',
    dayTemplate: 'heavy_training_day',
    calories: 660, proteinG: 42, fatG: 22, carbsG: 68,
    ingredients: [
      { name: 'Лосось', amount: 170, unit: 'г' },
      { name: 'Киноа', amount: 80, unit: 'г' },
      { name: 'Овощи микс', amount: 200, unit: 'г' },
      { name: 'Авокадо', amount: 0.5, unit: 'шт.' },
    ],
    dietaryTags: [DietaryRestriction.GLUTEN_FREE],
  },
];
